### ISSUE TITLE
Usunąć osoby pełnoletnie ale NS

### ISSUE THREAD

**Issue by katarzynazgodko** [itwzhp/SafeFromHarm#13]
Nie wyłapaliśmy tego niestety jak tworzyliśmy dokument, ale przecież mamy też pełnoletnich NSów którzy nie są intelektualnie w stanie przebrnąć przez szkolenie SFH. Usunęłabym ich na razie z listy osób które się powinny certyfikować, a przy kolejnej aktualizacji uchwały przekminym co z nimi zrobić

**Comment by karol-gro** [comment]
A mamy jakieś przewidywania, kiedy będzie aktualizacja?

**Comment by katarzynazgodko** [comment]
Była we wtorek w tym tygodniu, więc trochę wtopa że nie zdążyłam tego wyłapać. 
Na pewno będzie co roku, więc myślę że w przyszłym roku będzie aktualizacja uchwały. Natomiast to bym od razu wdrożyła, żeby tych NSów nie ścigać

**Comment by karol-gro** [comment]
Zmiana wrzucona po stronie API
