### ISSUE TITLE
Wysłać raport do chorągwi

### ISSUE THREAD

**Issue by karol-gro** [itwzhp/SafeFromHarm#2]
Dane obecnie wysyłane do hufca powinny iść też do chorągwi

**Comment by karol-gro** [comment]
Na teraz widzę dwa podejścia: 
1. wysyłamy osobnego maila do chorągwi. Będzie on dość długi i może chyba to sprawiać problemy
2. Do każdego maila do hufca dodajemy chorągiew do CC, więc mają wgląd 

Proponuję opcję 2, bo unikniemy problemu ze zbyt długim mailem (osób mogą być tysiące, zwłaszcza na początku)

**Comment by katarzynazgodko** [comment]
Marzeniem byłoby, żeby to była tabelka - ale ja nie wiem czy to jest możliwe.  
CC maili do hufców może przejść na tymczasie, chociaż chorągwie mnie za to rozwiązanie zjedzą. Tylko wtedy trzeba gdzieś dodać informacje, co to jest za hufiec - np. w tytule maila - bo na razie jej nie ma.

**Comment by karol-gro** [comment]
W osobnym zadaniu wysyłać maila do chorągwi z tabelką w excelu (CSV) z danymi:
- imię
- nazwisko
- nr ewidencyjny
- hufiec
- czy przeszkolony (albo data certyfikacji)

**Comment by katarzynazgodko** [comment]
Jeszcze jedna modyfikacja - tam gdzie mamy mianowanych pełnomocników Safe from Harm, to te zbiorcze tabelki powinny polecieć nie na ogólny mail Chorągwi, a do pełnomocników Chorągwianych.
Listę dołączam :) 
[Lista pełnomocników Chorągwianych_5058492.xlsx](https://github.com/itwzhp/SafeFromHarm/files/13249329/Lista.pelnomocnikow.Choragwianych_5058492.xlsx)

**Comment by karol-gro** [comment]
Ok, a ta lista gdzieś wisi aktualizowana na bieżąco? Jak nie to mogę gdzieś taką listę umieścić

**Comment by katarzynazgodko** [comment]
Tu ja mam - https://gkzhp.sharepoint.com/:x:/r/sites/SafeFromHarm-penomocnicychorgwiani/Shared%20Documents/General/Lista%20pe%C5%82nomocnik%C3%B3w%20Chor%C4%85gwianych_5058492.xlsx?d=w79686f5805934d77a00ad0c9572fc089&csf=1&web=1&e=cngKmF
